find_path(BITSTREAM_INCLUDE_DIR NAMES bitstream.hpp)
find_library(BITSTREAM_LIBRARY NAMES bitstream HINTS ${CPR_LIBRARY_ROOT})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(BITSTREAM REQUIRED_VARS BITSTREAM_LIBRARY BITSTREAM_INCLUDE_DIR)

if(BITSTREAM_FOUND)
    set(BITSTREAM_LIBRARIES ${BITSTREAM_LIBRARY})
    set(BITSTREAM_INCLUDE_DIRS ${BITSTREAM_INCLUDE_DIR})
endif()